Metrics/AbcSize:
  Max: 30

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Style/Documentation:
  Enabled: false

Style/FileName:
  Enabled: false

Style/IndentArray:
  EnforcedStyle: consistent

Style/IndentHash:
  EnforcedStyle: consistent

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/SpecialGlobalVars:
  Enabled: false
